let input = document.getElementById('input')
let buttonSeven = document.getElementById('seven')
let buttonEight = document.getElementById('eight')
let buttonNine = document.getElementById('nine')
let buttonDivident = document.getElementById('divi')
let buttonFour = document.getElementById('four')
let buttonFive = document.getElementById('five')
let buttonSix = document.getElementById('six')
let buttonMult = document.getElementById('mult')
let buttonOne = document.getElementById('one')
let buttonTwo = document.getElementById('two')
let buttonThree = document.getElementById('three')
let buttonadd = document.getElementById('add')
let buttonZero = document.getElementById('zero')
let buttonPoint= document.getElementById('point')
let buttonEqual = document.getElementById('equal')
let buttonMinus = document.getElementById('minus')

